# Generated by Django 4.0.2 on 2022-02-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=55)),
                ('secordName', models.CharField(max_length=55)),
                ('email_field', models.EmailField(max_length=255)),
                ('phoneNo', models.IntegerField(max_length=255)),
            ],
        ),
    ]
